# Generated by Django 4.2.7 on 2025-09-11 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם סוג העסק')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
            ],
            options={
                'verbose_name': 'סוג עסק',
                'verbose_name_plural': 'סוגי עסקים',
            },
        ),
        migrations.CreateModel(
            name='LicensingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='כותרת')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('authority', models.CharField(blank=True, max_length=200, verbose_name='רשות מוסמכת')),
                ('category', models.CharField(choices=[('restaurant', 'מסעדה'), ('bar', 'בר'), ('health', 'בריאות'), ('safety', 'בטיחות'), ('municipal', 'עירונית'), ('general', 'כללי')], default='general', max_length=20, verbose_name='קטגוריה')),
                ('priority', models.CharField(choices=[('high', 'גבוהה'), ('medium', 'בינונית'), ('low', 'נמוכה')], default='medium', max_length=10, verbose_name='עדיפות')),
                ('min_area', models.IntegerField(blank=True, null=True, verbose_name='שטח מינימלי')),
                ('max_area', models.IntegerField(blank=True, null=True, verbose_name='שטח מקסימלי')),
                ('min_capacity', models.IntegerField(blank=True, null=True, verbose_name='תפוסה מינימלית')),
                ('max_capacity', models.IntegerField(blank=True, null=True, verbose_name='תפוסה מקסימלית')),
                ('requires_gas', models.BooleanField(default=False, verbose_name='דורש גז')),
                ('meat_related', models.BooleanField(default=False, verbose_name='קשור לבשר')),
                ('delivery_related', models.BooleanField(default=False, verbose_name='קשור למשלוחים')),
                ('outdoor_related', models.BooleanField(default=False, verbose_name='קשור לישיבה בחוץ')),
                ('alcohol_related', models.BooleanField(default=False, verbose_name='קשור לאלכוהול')),
                ('estimated_cost', models.CharField(blank=True, max_length=100, verbose_name='עלות משוערת')),
                ('processing_time', models.CharField(blank=True, max_length=100, verbose_name='זמן טיפול')),
                ('business_types', models.ManyToManyField(to='questionnaire.businesstype', verbose_name='סוגי עסקים')),
            ],
            options={
                'verbose_name': 'דרישת רישוי',
                'verbose_name_plural': 'דרישות רישוי',
                'ordering': ['priority', 'category'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='שם העסק')),
                ('area_sqm', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='שטח במ״ר')),
                ('seating_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='מספר מקומות ישיבה')),
                ('uses_gas', models.BooleanField(default=False, verbose_name='משתמש בגז')),
                ('serves_meat', models.BooleanField(default=False, verbose_name='מגיש בשר')),
                ('offers_delivery', models.BooleanField(default=False, verbose_name='מציע משלוחים')),
                ('has_outdoor_seating', models.BooleanField(default=False, verbose_name='יש ישיבה בחוץ')),
                ('serves_alcohol', models.BooleanField(default=False, verbose_name='מגיש אלכוהול')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן בתאריך')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.businesstype', verbose_name='סוג העסק')),
            ],
            options={
                'verbose_name': 'הערכת עסק',
                'verbose_name_plural': 'הערכות עסקים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_generated_content', models.TextField(blank=True, verbose_name='תוכן שנוצר על ידי AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.businessassessment', verbose_name='הערכת עסק')),
                ('relevant_requirements', models.ManyToManyField(to='questionnaire.licensingrequirement', verbose_name='דרישות רלוונטיות')),
            ],
            options={
                'verbose_name': 'דוח הערכה',
                'verbose_name_plural': 'דוחות הערכה',
                'ordering': ['-created_at'],
            },
        ),
    ]
